version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building...
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
